"use client";

import React, { useState, useEffect } from "react";
import { useParams, useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Loader2, Sparkles, ChevronRight, CheckCircle2, AlertTriangle } from "lucide-react";
import { toast } from "sonner";

export default function SpecPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = React.use(params);
  const router = useRouter();
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [spec, setSpec] = useState<any>(null);

  useEffect(() => {
    const fetchSpec = async () => {
      try {
        const response = await fetch(`/api/projects/${id}/spec/ai-generate`, {
          method: "POST",
        });
        if (!response.ok) throw new Error("Failed to generate spec");
        const data = await response.json();
        setSpec(data);
      } catch (error) {
        toast.error("Failed to generate AI specification.");
      } finally {
        setLoading(false);
      }
    };

    fetchSpec();
  }, [id]);

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center min-h-screen space-y-4">
        <Loader2 className="h-12 w-12 animate-spin text-blue-600" />
        <p className="text-slate-600 font-medium">Gemini Pro is crafting your blueprint...</p>
      </div>
    );
  }

  if (!spec) {
    return (
      <div className="flex flex-col items-center justify-center min-h-screen space-y-4">
        <AlertTriangle className="h-12 w-12 text-amber-500" />
        <p className="text-slate-600">Something went wrong. Please try again.</p>
        <Button onClick={() => window.location.reload()}>Retry Generation</Button>
      </div>
    );
  }

  return (
    <div className="max-w-5xl mx-auto py-12 px-4 space-y-12">
      <header className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-slate-900">Project Specification</h1>
          <p className="text-slate-500 mt-1">Generated by Gemini Pro AI based on your raw idea.</p>
        </div>
        <div className="flex gap-3">
          <Button variant="outline">Edit Spec</Button>
          <Button className="bg-blue-600 hover:bg-blue-700 text-white" onClick={() => router.push(`/projects/${id}/architecture`)}>
            Continue to Architecture <ChevronRight className="ml-2 h-4 w-4" />
          </Button>
        </div>
      </header>

      <section className="space-y-6">
        <Card className="border-blue-100 bg-blue-50/50">
          <CardHeader>
            <CardTitle className="text-blue-900 flex items-center gap-2 text-xl">
              <Sparkles className="h-5 w-5" /> Executive Summary
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-slate-700 leading-relaxed text-lg italic">"{spec.executiveSummary}"</p>
          </CardContent>
        </Card>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div className="space-y-6">
            <h2 className="text-2xl font-bold text-slate-900">Core Features</h2>
            <div className="space-y-4">
              {spec.features.map((feature: any, i: number) => (
                <div key={i} className="p-4 rounded-xl border border-slate-200 bg-white shadow-sm space-y-2">
                  <div className="flex items-center justify-between">
                    <h3 className="font-bold text-slate-900">{feature.name}</h3>
                    <span className={`text-[10px] uppercase font-bold px-2 py-0.5 rounded-full ${
                      feature.priority === "must-have" ? "bg-red-100 text-red-700" : 
                      feature.priority === "should-have" ? "bg-amber-100 text-amber-700" : "bg-green-100 text-green-700"
                    }`}>
                      {feature.priority}
                    </span>
                  </div>
                  <p className="text-slate-600 text-sm leading-relaxed">{feature.description}</p>
                </div>
              ))}
            </div>
          </div>

          <div className="space-y-6">
            <h2 className="text-2xl font-bold text-slate-900">User Stories</h2>
            <div className="space-y-4">
              {spec.userStories.map((story: any, i: number) => (
                <div key={i} className="p-4 rounded-xl border border-slate-100 bg-slate-50 shadow-sm space-y-3">
                  <div className="space-y-1">
                    <h3 className="font-bold text-slate-900 text-sm">{story.title}</h3>
                    <p className="text-slate-600 text-sm italic">
                      "As a {story.asA}, I want {story.iWant} so that {story.soThat}."
                    </p>
                  </div>
                  <div className="space-y-1.5">
                    <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Acceptance Criteria</p>
                    <ul className="space-y-1">
                      {story.acceptanceCriteria.map((ac: string, j: number) => (
                        <li key={j} className="text-sm text-slate-700 flex items-start gap-2">
                          <CheckCircle2 className="h-4 w-4 text-green-500 mt-0.5 shrink-0" />
                          {ac}
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          <Card>
            <CardHeader><CardTitle className="text-lg">Success Criteria</CardTitle></CardHeader>
            <CardContent>
              <ul className="space-y-2">
                {spec.successCriteria.map((sc: string, i: number) => (
                  <li key={i} className="text-sm text-slate-600 flex items-start gap-2">
                    <div className="h-1.5 w-1.5 rounded-full bg-blue-500 mt-1.5 shrink-0" />
                    {sc}
                  </li>
                ))}
              </ul>
            </CardContent>
          </Card>

          <Card>
            <CardHeader><CardTitle className="text-lg">Known Risks</CardTitle></CardHeader>
            <CardContent>
              <ul className="space-y-2">
                {spec.knownRisks.map((risk: string, i: number) => (
                  <li key={i} className="text-sm text-slate-600 flex items-start gap-2">
                    <div className="h-1.5 w-1.5 rounded-full bg-amber-500 mt-1.5 shrink-0" />
                    {risk}
                  </li>
                ))}
              </ul>
            </CardContent>
          </Card>

          <Card className="md:col-span-1">
            <CardHeader><CardTitle className="text-lg">Development Phases</CardTitle></CardHeader>
            <CardContent>
              <div className="space-y-4">
                {spec.phases.map((phase: any, i: number) => (
                  <div key={i} className="flex items-center gap-3">
                    <div className="h-8 w-8 rounded-full bg-slate-100 flex items-center justify-center text-xs font-bold text-slate-600 shrink-0">
                      {i + 1}
                    </div>
                    <div>
                      <p className="text-sm font-bold text-slate-900">{phase.name}</p>
                      <p className="text-[11px] text-slate-400 font-medium">{phase.estimatedDays} days estimated</p>
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </div>
      </section>
    </div>
  );
}
